# Generated by Django 3.1.7 on 2021-10-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('shopname', models.CharField(max_length=200)),
                ('phone_number', models.BigIntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('nid', models.BigIntegerField(max_length=30)),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_number', models.BigIntegerField(max_length=11)),
            ],
        ),
    ]
