# Generated by Django 3.1.7 on 2021-10-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.BigIntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('customers', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('products', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
